### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by over-flo** [dvdln/jsonpath-object-transform#1]
Hi,

When i include jsonpath-object-transform module i have the following exception :

Error: Cannot find module 'lib/jsonpath-object-transform.js'

I seems that changing index.js
from : module.exports = require('lib/jsonpath-object-transform.js');
to : module.exports = require('./lib/jsonpath-object-transform.js');

fixes the issue

Regards

**Comment by Wayfarer247** [comment]
Just ran into this as well.

**Comment by freder** [comment]
so this is fixed, but not yet pushed to npm?

**Comment by ethanmick** [comment]
Correct. We forked the repo and then added this to our `package.json`:

```
"jsonpath-object-transform": "cloudmine/jsonpath-object-transform",
```

This way, if this repo is ever updated, we won't be surprised with a new version, and we know our version will never change. You could also fork it and upload it to NPM yourself, but I didn't want to step on anyone's toes.

**Comment by dvdln** [comment]
I've been pretty bad about keeping up with my hobbies… but yes, this is [published to npm](https://www.npmjs.com/package/jsonpath-object-transform) now. Sorry about that :-\

**Comment by ethanmick** [comment]
:clap: Great to hear!
