### ISSUE TITLE
Switch to another jsonpath library

### ISSUE THREAD

**Issue by nuclearspike** [dvdln/jsonpath-object-transform#8]
The JSONPath library is notoriously slow for queries. In a 5000 item array, telling it to fetch index 400 takes 5 *seconds* on my rather fast laptop. The ["jsonpath" library](https://github.com/dchester/jsonpath) is orders of magnitude faster. When I tested it to just find items matching a predicate with the same list, it took 6ms.

When using queries in templates in this library therefore suffer the same terrible performance. Having it perform a query that was selective (filtering by properties then returning only the ids of the matching items) jsonpath took 14 **milliseconds** while JSONPath took 37 **seconds**. It's not just a little bit faster but the difference is so significant that JSONPath should be shut down or fixed because it's simply not good enough for production quality code.

JSONPath has some additional syntax outside of the spec, but I don't think they are needed for most transforms. JSONPath (by the test I mentioned) is 2700x slower. Nobody should be using that library.

**Comment by dvdln** [comment]
I think [this approach](https://github.com/dvdln/jsonpath-object-transform/issues/7) is a little better. You pick your own parser—jsonPath or not
